### ISSUE TITLE
[1.12.2] Right-clicking stairs with consumables works

### ISSUE THREAD

**Issue by CREEATION** [trikzon/Snow-Variants#1]
It removes one consumable item from your inventory and adds the snow layer to the stair.
Food, potions, you name it.

(I was initially also going to submit an issue about the snow layer not being applied at all sometimes, then I realized I have to actually target one of the top sides of the stair. That was a little confusing 🐢 )

**Comment by Trikzon** [comment]
That is interesting.... After I am done updating my other mod 'Nether Gold' to 1.13.2 I am going to be backporting this mod to 1.12.2 because the way I coded it for 1.13.2 is much more efficient and cleaner to read.

If this problem also happens in 1.13.2 I will be looking into it, otherwise the back port will fix it.

Also, the requirement for looking at the top of the stair/slab is to prevent problems where right clicking on the side will also place a snow layer along with converting the star/slab.

**Comment by CREEATION** [comment]
I see. It does work for 1.13.2. Waiting for the port then, thanks!

**Comment by Trikzon** [comment]
Great to here! It shouldn't be too long as the 'Nether Gold' port is almost complete

**Comment by Trikzon** [comment]
c0a7c0b0a29998a8ff15e052908ee20e3e945482
Fixed and now published on curse. Thanks for reporting!
