### ISSUE TITLE
1.12.2 Serene Seasons Compatibility

### ISSUE THREAD

**Issue by SlimF** [trikzon/Snow-Variants#10]
As of version 1.12.2-1.3.1 slabs and stairs turn into their snowy variant only if they are in a snowy biome even if it's winter season and it's snowing in every biome (minus the sand biomes). 
Would it be possible to implement compatibility between the two mods so that the slabs and stairs would turn into their snowy counterpart when it's winter ?

**Comment by Trikzon** [comment]
Currently, the way it works is that it checks the "temperature" of the biome and whether it is raining to make this feature turn on for that block. This is because in vanilla rain and snow are the same thing, just with the biome temperature "choosing" which one gets used.

I could look into adding compatibility soon though, it should be possible as long as they have a good api

**Comment by SlimF** [comment]
Fingers crossed. Thank you for the fast reply and the explanation !

**Comment by mactso** [comment]
I'm also interested in seasonal (there are a couple of seasonal packs) compatible snow.

I'm using your pack now just to make some things look neat for screen shots but snow on stairs and half slabs naturally would be fantastic.
