### ISSUE TITLE
 snowvariants-1.12.2-1.0.1.jar wood stairs and slabs work not with snow

### ISSUE THREAD

**Issue by Titoo8899** [trikzon/Snow-Variants#2]
Hi,
the 1.12.2 version 1.0.1 work with all other slabs and stairs normal. Only wood work not and become by right click not the snow texture. Please fix this bug.

**Comment by Trikzon** [comment]
That is interesting. I'll check it out. Do note that a new version is in the works but will take sometime as I am rewriting a lot of the code to make it possible to easily add compatibility for other mod's slabs/stairs and a lot of bugs will be fixed with it. I'll respond to this thread when it is fixed

**Comment by Trikzon** [comment]
c0a7c0b0a29998a8ff15e052908ee20e3e945482
Fixed and now published on curse. Thanks for reporting!
